# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_win64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_win64)
  cpp_game_config = debug_win64

else ifeq ($(config),debug_linux64)
  cpp_game_config = debug_linux64

else ifeq ($(config),release_win64)
  cpp_game_config = release_win64

else ifeq ($(config),release_linux64)
  cpp_game_config = release_linux64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := cpp-game

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

cpp-game:
ifneq (,$(cpp_game_config))
	@echo "==== Building cpp-game ($(cpp_game_config)) ===="
	@${MAKE} --no-print-directory -C cpp-game -f Makefile config=$(cpp_game_config)
endif

clean:
	@${MAKE} --no-print-directory -C cpp-game -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_win64"
	@echo "  debug_linux64"
	@echo "  release_win64"
	@echo "  release_linux64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   cpp-game"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"